# theme: jekyll-theme-cayman
remote_theme: lewismiddleton/cayman-dark
title: iOS App Development Basics
description: A simple Blog which helps to learn/recall the basics of iOS App Development using Swift Programming Language.
author: Arunprasadh C
